clear;
clc;

CO2num = 0;
COnum = 0;
O2num = 0;
H2num = 0;

W = input('LATTICE W =');
L = W; 

CH4 = 1; CH3 = 2; CH2 = 3; CH = 4; C = 5; C2 = 6; C3 = 7; H2O = 8; OH = 9; O = 10; H = 11; O2 = 12; H2 = 13; CO = 14; CO2 = 15; C2H2 = 16; COOH = 17;R=8.314;

CNum = 0;
C2Num = 0;
C3Num = 0;
HNum = 0;
ONum = 0;

CH4dissociationNum = 0; CH4productionNum = 0;
CH3dissociationNum = 0; CH3productionNum = 0;
CH2dissociationNum = 0; CH2productionNum = 0;
CHdissociationNum = 0; CHproductionNum = 0;

H2OadsorptionNum = 0; 
H2OdissociationNum = 0; H2OproductionNum = 0;
OHdissociationNUm = 0; OHproductionNum = 0;
OHdimerreactionNum = 0; OHdimerproductionNum = 0;

H2productionNum = 0; H2dissociationNum = 0;
O2productionNum = 0; O2dissociationNum = 0;

CH4oxidationNum = 0; CH4deoxidationNum = 0;
CH3hydroxideNum = 0; CH3dehydroxideNum = 0;
CH3oxidationNum = 0; CH3deoxidationNum = 0; 
CH2hydroxideNum = 0; CH2dehydroxideNum = 0;
CH2oxidationNum = 0; CH2deoxidationNum = 0; 
CHhydroxideNum = 0; CHdehydroxideNum = 0;
CHoxidationANum = 0; CHdeoxidationANum = 0; 
CHoxidationBNum = 0; CHdeoxidationBNum = 0; 
C2H2productionNum = 0; C2H2dissociationNum = 0;

CoxidationNum = 0; CdeoxidationNum = 0; 
COoxidationNum = 0; COdeoxidationNum = 0; 
COdesorptionNum = 0; COadsorptionNum = 0;
CO2desorptionNum = 0; CO2adsorptionNum = 0;
COOHformationANum = 0; COOHdissociationANum = 0; %CO+OH-->COOH
COOHformationBNum = 0; COOHdissociationBNum = 0; %CO2+H-->COOH

C2formationNum = 0; C2dissociationNum = 0;
C3formationNum = 0; C3dissociationNum = 0;

HdiffusionNum = 0; OdiffusionNum = 0; CdiffusionNum = 0; C3diffusionNum = 0; 



trap1=0;trap2=0;

tem = input('Temperature(C) =');
PS = input('print step =');
d = W * 0.255;
T = tem + 273.15; % the temperature of the system
t = 0; step = 0; count = 0; %initialization of the time and steps
Conf = zeros(W,L); %initialization of the lattice configurations

CH4dissociationSP(1,1) = 2; CH4dissociationSP(1,L) = 2; CH4dissociationSP(W,1) = 2; CH4dissociationSP(W,L) = 2; 
CH4dissociationSP(2:(W-1),1) = 3; CH4dissociationSP(2:(W-1),L) = 3; CH4dissociationSP(1,2:(L-1)) = 3; 
CH4dissociationSP(W,2:(L-1)) = 3; CH4dissociationSP(2:(W-1),2:(L-1)) = 4;

CH4productionSP = zeros(W, L);
CH3dissociationSP = zeros(W, L); CH3productionSP = zeros(W, L);
CH2dissociationSP = zeros(W, L); CH2productionSP = zeros(W, L);
CHdissociationSP = zeros(W, L); CHproductionSP = zeros(W, L);

H2OadsorptionSP = ones(W, L); 
H2OdissociationSP = zeros(W, L); H2OproductionSP = zeros(W, L);
OHdissociationSP = zeros(W, L); OHproductionSP = zeros(W, L);
OHdimerreactionSP = zeros(W, L); OHdimerproductionSP = zeros(W, L);
O2productionSP = zeros(W, L);
H2productionSP = zeros(W, L);

CH4oxidationSP = zeros(W, L); CH4deoxidationSP = zeros(W, L);
CH3hydroxideSP = zeros(W, L); CH3dehydroxideSP = zeros(W, L);
CH3oxidationSP = zeros(W, L); CH3deoxidationSP = zeros(W, L); 
CH2hydroxideSP = zeros(W, L); CH2dehydroxideSP = zeros(W, L);
CH2oxidationSP = zeros(W, L); CH2deoxidationSP = zeros(W, L); 
CHhydroxideSP = zeros(W, L); CHdehydroxideSP = zeros(W, L);
CHoxidationASP = zeros(W, L); CHdeoxidationASP = zeros(W, L); 
CHoxidationBSP = zeros(W, L); CHdeoxidationBSP = zeros(W, L);
C2H2productionSP = zeros(W, L); C2H2dissociationSP = zeros(W, L);

CoxidationSP = zeros(W, L); CdeoxidationSP = zeros(W, L);
COoxidationSP = zeros(W, L); COdeoxidationSP = zeros(W, L); 
CO2desorptionSP = zeros(W, L); CO2adsorptionSP = ones(W, L);
COdesorptionSP = zeros(W, L); COadsorptionSP = ones(W, L);
COOHformationASP = zeros(W, L); COOHdissociationASP = zeros(W, L);
COOHformationBSP = zeros(W, L); COOHdissociationBSP = zeros(W, L);

C2formationSP = zeros(W, L); C2dissociationSP = zeros(W, L);
C3formationSP = zeros(W, L); C3dissociationSP = zeros(W, L);

CdiffusionSP = zeros(W, L); C3diffusionSP = zeros(W, L); HdiffusionSP = zeros(W, L); OdiffusionSP = zeros(W, L); 

rate = zeros(1,55);%initialization of the reaction rate

NZE = zeros(1,55);%initialization of the sites number for each species: non-zero elements in each event matrix

NZE(1) = nnz(CH4dissociationSP);
NZE(9) = nnz(H2OadsorptionSP);
NZE(41) = nnz(CO2adsorptionSP);
NZE(43) = nnz(COadsorptionSP);

s = W*L; % Total site on the lattice

[A]=kineticparameters(T); % Calculation of the pre-exponnatianl factor
g=[];

while t < 36000 || coverage < 0.6
    %tic
    step = step+1;
    coverage = (CNum + C2Num + C3Num) / s; % The carbon atoms surface coverage on the lattice
    [Ea] = energybarrier(coverage);
    k = A .* exp(-Ea ./ (8.314 * T));
    rate = k .* NZE;

    RN = rand(1);

            totalrate = sum(rate);
            %pick up the event i
            if RN <= rate(1) / totalrate
                [NZE, Conf, CH4productionSP, CH4deoxidationSP, CH3hydroxideSP, CH3oxidationSP, CH3productionSP, CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, ...
                	H2productionSP, CHdeoxidationBSP, COOHformationBSP, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, ...
                	OHdissociationSP, CH4oxidationSP, C2H2dissociationSP, CdeoxidationSP, COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, ...
                	C2dissociationSP, C3dissociationSP, HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP, CH4dissociationSP] = CH4dissociation(NZE, W, L, Conf, CH3, CH2, CH, ...
                	C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4productionSP, CH3productionSP, CH2productionSP, CHproductionSP, H2OdesorptionSP, H2OproductionSP, OHproductionSP, ...
                	CoxidationSP, COoxidationSP, COdesorptionSP, CO2desorptionSP, C2formationSP, C3formationSP, H2productionSP, O2productionSP, C2H2productionSP, ...
                	HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP);
                CH4dissociationNum = CH4dissociationNum + 1;
                HNum = HNum+1;

            elseif RN <= (sum(rate(1:2))/totalrate)
                [NZE, Conf, CH4deoxidationSP, CH3hydroxideSP, CH3oxidationSP, CH4productionSP, CH3productionSP, CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, ...
                	H2productionSP, CHdeoxidationBSP, COOHformationBSP, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, ...
                	CH4oxidationSP, C2H2dissociationSP, CdeoxidationSP, COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, ...
                	C3dissociationSP, HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP, CH4dissociationSP] = CH4production(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, ...
                	CO2, COOH, C2, C3, CH3productionSP, CH4oxidationSP, CH3dehydroxideSP, CH3deoxidationSP, CH4dissociationSP, CH3dissociationSP, CH2dissociationSP, ...
                	CHdissociationSP, H2OdissociationSP, OHdissociationSP, CHoxidationASP, COOHdissociationBSP, HdiffusionSP);
                CH4productionNum = CH4productionNum + 1;
                HNum = HNum-1;

            elseif RN <= (sum(rate(1:3))/totalrate)
                [NZE, Conf, CH4deoxidationSP, CH3hydroxideSP, CH3oxidationSP, CH4productionSP, CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, ...
                	H2productionSP, CHdeoxidationBSP, COOHformationBSP, CH3dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, ...
                	CH4oxidationSP, C2H2dissociationSP, CdeoxidationSP, COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, ...
                	C2dissociationSP, C3dissociationSP, HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP, CH3productionSP, CH2dissociationSP, CH3dehydroxideSP, ...
                	CH3deoxidationSP, CH2hydroxideSP, CH2oxidationSP] = CH3dissociation(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, ...
                	CH4dissociationSP, CH4oxidationSP, CH3dehydroxideSP, CH3deoxidationSP, CH4productionSP, CH3productionSP, CH2productionSP, CHproductionSP, ...
                	H2OproductionSP, OHproductionSP, O2productionSP, H2productionSP, CH4deoxidationSP, C2H2productionSP, CoxidationSP, COoxidationSP, COdesorptionSP, ...
                	CO2desorptionSP, COOHformationASP, COOHformationBSP, C2formationSP, C3formationSP,HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP);
                CH3dissociationNum = CH3dissociationNum + 1;
                HNum = HNum+1;

            elseif RN <= (sum(rate(1:4))/totalrate)
                [NZE, Conf, CH4deoxidationSP, CH3hydroxideSP, CH3oxidationSP, CH4productionSP, CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, ...
                	H2productionSP, CHdeoxidationBSP, COOHformationBSP, CH3dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, ...
                	CH4oxidationSP, C2H2dissociationSP, CdeoxidationSP, COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, ...
                	C2dissociationSP, C3dissociationSP, HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP, CH3productionSP, CH2dissociationSP, CH3dehydroxideSP, ...
                	CH3deoxidationSP, CH2hydroxideSP, CH2oxidationSP] = CH3production(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, ...
                	CH4dissociationSP, CH2dissociationSP, CHdissociationSP, H2OdissociationSP, OHdissociationSP, CHoxidationASP, COOHdissociationBSP, HdiffusionSP, ...
                	CH3dissociationSP, CH2productionSP, CH3hydroxideSP, CH3oxidationSP, CH2dehydroxideSP, CH2deoxidationSP);
                CH3productionNum =CH3productionNum+ 1;
                HNum = HNum-1;

            elseif RN <= (sum(rate(1:5))/totalrate)
                [NZE, Conf, CH4productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, H2productionSP, CHdeoxidationBSP,  COOHformationBSP, CH3dissociationSP, ...
                	H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, CH4oxidationSP, C2H2dissociationSP, CdeoxidationSP, COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, ...
                	COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP, CH3productionSP, ...
                	CH2dissociationSP, CH3dehydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2oxidationSP, CH2productionSP, CHdissociationSP, CH2dehydroxideSP, ...
                	CHhydroxideSP, CHoxidationASP, CHoxidationBSP, C2H2productionSP] = CH2dissociation(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, ...
                	CH4productionSP, CH3productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, O2productionSP, H2productionSP,CH4deoxidationSP, ...
                	C2H2productionSP, CoxidationSP, COoxidationSP, COdesorptionSP, CO2desorptionSP, COOHformationASP, COOHformationBSP, C2formationSP, C3formationSP, ...
                	HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP, CH3dissociationSP, CH2productionSP, CH3hydroxideSP, CH3oxidationSP, CH2dehydroxideSP, CH2deoxidationSP);
                CH2dissociationNum = CH2dissociationNum+1;
                HNum = HNum+1;

            elseif RN <= (sum(rate(1:6))/totalrate)
            	[NZE, Conf, CH4productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, H2productionSP, CHdeoxidationBSP, COOHformationBSP, CH3dissociationSP, H2OadsorptionSP, ...
            		H2OdissociationSP, OHdissociationSP, CH4oxidationSP, C2H2dissociationSP, CdeoxidationSP, COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, ...
            		COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP, CH3productionSP, CH2dissociationSP, ...
            		CH3dehydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2oxidationSP, CH2productionSP, CHdissociationSP, CH2dehydroxideSP, CHhydroxideSP, CHoxidationASP, ...
            		CHoxidationBSP, C2H2productionSP] = CH2production(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4dissociationSP, CH3dissociationSP, ...
            		CHdissociationSP, H2OdissociationSP, OHdissociationSP, CHoxidationASP, COOHdissociationBSP, HdiffusionSP, CH2dissociationSP, CHproductionSP, CH2hydroxideSP, ...
            		CH2oxidationSP, CHdehydroxideSP, CHdeoxidationASP, CHdeoxidationBSP, C2H2dissociationSP);
                CH2dissociationNum = CH2dissociationNum+1;
                HNum = HNum-1;

            elseif RN <= (sum(rate(1:7))/totalrate)
            	[NZE, Conf, CH4productionSP, CH3productionSP, H2OproductionSP, OHproductionSP, H2productionSP, CHdeoxidationBSP,COOHformationBSP, CH3dissociationSP, ...
            		CH2dissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, CH4oxidationSP, C2H2dissociationSP, CdeoxidationSP, COdeoxidationSP, ...
            		COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, OdiffusionSP, CdiffusionSP, ...
            		C3diffusionSP, CH2productionSP, CHdissociationSP, CH2dehydroxideSP, CHhydroxideSP, CHoxidationASP, CHoxidationBSP, C2H2productionSP, CHproductionSP, ...
            		CHdehydroxideSP, CHdeoxidationASP, CoxidationSP, C2formationSP, C3formationSP] = CHdissociation(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, ...
            		OH, O, CO, CO2, COOH, C2, C3, CH4productionSP, CH3productionSP, CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, O2productionSP, ...
            		H2productionSP,CH4deoxidationSP, C2H2productionSP, CoxidationSP, COoxidationSP, COdesorptionSP, CO2desorptionSP, COOHformationASP, COOHformationBSP, ...
            		C2formationSP, C3formationSP,HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP, CH2dissociationSP, CHproductionSP, CH2hydroxideSP, ...
            		CH2oxidationSP, CHdehydroxideSP, CHdeoxidationASP, CHdeoxidationBSP, C2H2dissociationSP);
                CHdissociationNum = CHdissociationNum+1;
                HNum = HNum+1;

            elseif RN <= (sum(rate(1:8))/totalrate)
            	[NZE, Conf, CH4productionSP, CH3productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, H2productionSP, CHdeoxidationBSP, COOHformationBSP, ...
            		CH3dissociationSP, CH2dissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, CH4oxidationSP, C2H2dissociationSP, CdeoxidationSP, ...
            		COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, ...
            		OdiffusionSP, CdiffusionSP, C3diffusionSP, CH2productionSP, CHdissociationSP, CH2dehydroxideSP, CHhydroxideSP, CHoxidationASP, CHoxidationBSP, ...
            		C2H2productionSP] = CHproduction(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4dissociationSP, CH3dissociationSP, ...
            		CH2dissociationSP, H2OdissociationSP, OHdissociationSP, COOHdissociationBSP, HdiffusionSP, CHdissociationSP, CHhydroxideSP, CHoxidationASP, ...
            		CdeoxidationSP, C2dissociationSP, C3dissociationSP, CdiffusionSP);
                CHproductionNum = CHproductionNum+1;
                HNum = HNum-1;

            elseif RN <= (sum(rate(1:9))/totalrate)
                [NZE, Conf, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, OHdissociationSP, CH4oxidationSP, C2H2dissociationSP, CdeoxidationSP, ...
                	COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, ...
                	OdiffusionSP, CdiffusionSP, C3diffusionSP, H2OdissociationSP, OHdimerproductionSP, CH3dehydroxideSP, CH2dehydroxideSP, CHdehydroxideSP] = H2Oadsorption(NZE, W, L, ...
                	Conf,CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4productionSP, CH3productionSP, CH2productionSP, CHproductionSP, H2OproductionSP, ...
                	OHproductionSP, O2productionSP, H2productionSP,CH4deoxidationSP, C2H2productionSP, CoxidationSP, COoxidationSP, COdesorptionSP, CO2desorptionSP, ...
                	COOHformationASP, COOHformationBSP, C2formationSP, C3formationSP,HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP);
				H2OadsorptionNum = H2OadsorptionNum+1;

			elseif RN <= (sum(rate(1:10))/totalrate)
                [NZE, Conf, CH4productionSP, CH3productionSP, CH2productionSP, CHproductionSP, OHproductionSP, H2productionSP, CHdeoxidationBSP,COOHformationBSP, CH3dissociationSP, ...
                	CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, CH4oxidationSP, C2H2dissociationSP, CdeoxidationSP, COdeoxidationSP, COadsorptionSP, ...
                	CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP, ...
                	H2OproductionSP, OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, CH3hydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2deoxidationSP, CHhydroxideSP, ...
                	CHdeoxidationASP,COOHformationASP] = H2Odissociation(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4productionSP, CH3productionSP, ...
                	CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, O2productionSP, H2productionSP,CH4deoxidationSP, C2H2productionSP, CoxidationSP, ...
                	COoxidationSP, COdesorptionSP, CO2desorptionSP, COOHformationASP, COOHformationBSP, C2formationSP, C3formationSP,HdiffusionSP, OdiffusionSP, CdiffusionSP, ...
                	C3diffusionSP, H2OadsorptionSP, OHdimerreactionSP, CH3hydroxideSP, CH2hydroxideSP, CHhydroxideSP);
                H2OdissociationNum = H2OdissociationNum+1;
                HNum = HNum+1;

            elseif RN <= (sum(rate(1:11))/totalrate)
                [NZE, Conf, CH4productionSP, CH3productionSP, CH2productionSP, CHproductionSP, OHproductionSP, H2productionSP, CHdeoxidationBSP, COOHformationBSP, CH3dissociationSP, ...
                	CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, CH4oxidationSP, C2H2dissociationSP, CdeoxidationSP, COdeoxidationSP, COadsorptionSP, ...
                	CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP, ...
                	H2OproductionSP, OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, CH3hydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2deoxidationSP, CHhydroxideSP, ...
                	CHdeoxidationASP,COOHformationASP] = H2Oproduction(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4dissociationSP, CH3dissociationSP, ...
                	CH2dissociationSP, CHdissociationSP, H2OdissociationSP, OHdissociationSP, CHoxidationASP, COOHdissociationBSP, HdiffusionSP, H2OdissociationSP, OHproductionSP, ...
                	OHdimerproductionSP, CH4oxidationSP, CH3dehydroxideSP, CH3oxidationSP, CH2dehydroxideSP, CH2oxidationSP, CHdehydroxideSP, CHoxidationASP, COOHdissociationASP);
                H2OproductionNum = H2OproductionNum+1;
                HNum = HNum-1;

            elseif RN <= (sum(rate(1:12))/totalrate)
                [NZE, Conf, CH4productionSP, CH3productionSP, CH2productionSP, CHproductionSP, H2productionSP, CHdeoxidationBSP,COOHformationBSP, CH3dissociationSP, CH2dissociationSP, ...
                	CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, C2H2dissociationSP, CdeoxidationSP, COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, ...
                	COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, CdiffusionSP, C3diffusionSP, H2OproductionSP, OHdissociationSP, OHdimerreactionSP, ...
                	CH4deoxidationSP, CH3hydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2deoxidationSP, CHhydroxideSP, CHdeoxidationASP,COOHformationASP, OHproductionSP, ...
                	OHdimerproductionSP, O2productionSP, CH4oxidationSP, CH3oxidationSP, CH2oxidationSP, CHoxidationASP, CHoxidationBSP, CoxidationSP, COoxidationSP, ...
                	OdiffusionSP] = OHdissociation(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4productionSP, CH3productionSP, CH2productionSP, ...
                	CHproductionSP, H2OproductionSP, O2productionSP, H2productionSP,CH4deoxidationSP, C2H2productionSP, CoxidationSP, COoxidationSP, COdesorptionSP, CO2desorptionSP, ...
                	COOHformationASP, COOHformationBSP, C2formationSP, C3formationSP,HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP, H2OdissociationSP, OHproductionSP, ...
                	OHdimerproductionSP, CH4oxidationSP, CH3dehydroxideSP, CH3oxidationSP, CH2dehydroxideSP, CH2oxidationSP, CHdehydroxideSP, CHoxidationASP, COOHdissociationASP);
                OHdissociationNum = OHdissociationNum+1;
                HNum = HNum+1;
                ONum = ONum+1;

            elseif RN <= (sum(rate(1:13))/totalrate)
                [NZE, Conf, CH4productionSP, CH3productionSP, CH2productionSP, CHproductionSP, H2productionSP, CHdeoxidationBSP,COOHformationBSP, CH3dissociationSP, CH2dissociationSP, ...
                	CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, C2H2dissociationSP, CdeoxidationSP, COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, ...
                	COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, CdiffusionSP, C3diffusionSP, H2OproductionSP, OHdissociationSP, OHdimerreactionSP, ...
                	CH4deoxidationSP, CH3hydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2deoxidationSP, CHhydroxideSP, CHdeoxidationASP,COOHformationASP, OHproductionSP, ...
                	OHdimerproductionSP, O2productionSP, CH4oxidationSP, CH3oxidationSP, CH2oxidationSP, CHoxidationASP, CHoxidationBSP, CoxidationSP, COoxidationSP, OdiffusionSP] = OHproduction(NZE, W, L, ...
                	Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4dissociationSP, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OdissociationSP, ...
                	OHdissociationSP, CHoxidationASP, COOHdissociationBSP, HdiffusionSP, OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, CH3deoxidationSP, CH2deoxidationSP, ...
                	CHdeoxidationASP, CHdeoxidationBSP, CdeoxidationSP, COdeoxidationSP,OdiffusionSP);
                OHproductionNum = OHproductionNum+1;
                HNum = HNum-1;
                ONum = ONum-1;

            elseif RN <= (sum(rate(1:14))/totalrate)
                [NZE, Conf, H2OproductionSP, OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, CH3hydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2deoxidationSP, CHhydroxideSP, ...
                	CHdeoxidationASP,COOHformationASP, OHproductionSP, OHdimerproductionSP, O2productionSP, CH4oxidationSP, CH3oxidationSP, CH2oxidationSP, CHoxidationASP, ...
                	CHoxidationBSP, CoxidationSP, COoxidationSP, OdiffusionSP] = OHdimerreaction(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3,...
                	H2OdissociationSP, OHproductionSP, OHdimerproductionSP, CH4oxidationSP, CH3dehydroxideSP, CH3oxidationSP, CH2dehydroxideSP, CH2oxidationSP, CHdehydroxideSP, ...
                	CHoxidationASP, COOHdissociationASP);
                OHdimerreactionNum = OHdimerreactionNum+1;

            elseif RN <= (sum(rate(1:15))/totalrate)
                [NZE, Conf, H2OproductionSP, OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, CH3hydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2deoxidationSP, CHhydroxideSP, ...
                	CHdeoxidationASP,COOHformationASP, OHproductionSP, OHdimerproductionSP, O2productionSP, CH4oxidationSP, CH3oxidationSP, CH2oxidationSP, CHoxidationASP, ...
                	CHoxidationBSP, CoxidationSP, COoxidationSP, OdiffusionSP] = OHdimerproduction(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, H2OadsorptionSP, ...
                	H2OproductionSP, OHdimerreactionSP, CH3hydroxideSP, CH2hydroxideSP, CHhydroxideSP, OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, CH3deoxidationSP, ...
                	CH2deoxidationSP, CHdeoxidationASP, CHdeoxidationBSP, CdeoxidationSP, COdeoxidationSP,OdiffusionSP);
                OHdimerproductionNum = OHdimerproductionNum+1;

            elseif RN <= (sum(rate(1:16))/totalrate)
                [NZE, Conf, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, C2H2dissociationSP, CdeoxidationSP, ...
                	COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, CdiffusionSP, ...
                	C3diffusionSP, CH4dissociationSP, OHproductionSP, OHdimerproductionSP, O2productionSP, CH4oxidationSP, CH3oxidationSP, CH2oxidationSP, CHoxidationASP, ...
                	CHoxidationBSP, CoxidationSP, COoxidationSP, OdiffusionSP] = O2production(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3,...
                    OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, CH3deoxidationSP, CH2deoxidationSP, CHdeoxidationASP, CHdeoxidationBSP, CdeoxidationSP, COdeoxidationSP, OdiffusionSP);
                O2productionNum = O2productionNum+1;
                ONum = ONum-2;
                O2Num = O2Num+1;

            elseif RN <= (sum(rate(1:17))/totalrate)
                [NZE, Conf, CH4productionSP, CH3productionSP, CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, H2productionSP, CHdeoxidationBSP,COOHformationBSP, ...
                	CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, CH4oxidationSP, C2H2dissociationSP, CdeoxidationSP, ...
                	COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, OdiffusionSP, ...
                	CdiffusionSP, C3diffusionSP, CH4dissociationSP] = H2production(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4dissociationSP, ...
                	CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OdissociationSP, OHdissociationSP, CHoxidationASP, COOHdissociationBSP, HdiffusionSP);
                H2productionNum = H2productionNum+1;
                HNum = HNum-2;
                H2Num = H2Num+1;

            elseif RN <= (sum(rate(1:18))/totalrate)
                [NZE, Conf, CH4productionSP, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, C2H2dissociationSP, CdeoxidationSP, COdeoxidationSP, COadsorptionSP, ...
                	CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, CdiffusionSP, C3diffusionSP, H2OproductionSP, ...
                	OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, CH3hydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2deoxidationSP, CHhydroxideSP, CHdeoxidationASP, ...
                	COOHformationASP, OHproductionSP, OHdimerproductionSP, O2productionSP, CH4oxidationSP, CH3oxidationSP, CH2oxidationSP, CHoxidationASP, CHoxidationBSP, ...
                	CoxidationSP, COoxidationSP, OdiffusionSP] = CH4oxidation(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4productionSP, ...
                	CH3productionSP, CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, O2productionSP, H2productionSP,CH4deoxidationSP, C2H2productionSP, ...
                	CoxidationSP, COoxidationSP, COdesorptionSP, CO2desorptionSP, COOHformationASP, COOHformationBSP, C2formationSP, C3formationSP,HdiffusionSP, OdiffusionSP, ...
                	CdiffusionSP, C3diffusionSP, OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, CH3deoxidationSP, CH2deoxidationSP, CHdeoxidationASP, CHdeoxidationBSP, ...
                	CdeoxidationSP, COdeoxidationSP,OdiffusionSP);
                CH4oxidationNum = CH4oxidationNum+1;
                ONum = ONum-1;

            elseif RN <= (sum(rate(1:19))/totalrate)
                [NZE, Conf, CH4productionSP, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, C2H2dissociationSP, CdeoxidationSP, ...
                	COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, CdiffusionSP, ...
                	C3diffusionSP, H2OproductionSP, OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, CH3hydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2deoxidationSP, ...
                	CHhydroxideSP, CHdeoxidationASP, COOHformationASP, OHproductionSP, OHdimerproductionSP, O2productionSP, CH4oxidationSP, CH3oxidationSP, CH2oxidationSP, ...
                	CHoxidationASP, CHoxidationBSP, CoxidationSP, COoxidationSP, OdiffusionSP] = CH4deoxidation(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3,...
                	CH4dissociationSP, CH3productionSP, CH4oxidationSP, CH3dehydroxideSP, CH3deoxidationSP, H2OdissociationSP, OHproductionSP, OHdimerproductionSP, CH4oxidationSP, ...
                	CH3dehydroxideSP, CH3oxidationSP, CH2dehydroxideSP, CH2oxidationSP, CHdehydroxideSP, CHoxidationASP, COOHdissociationASP);
                CH4deoxidationNum = CH4deoxidationNum+1;
                ONum = ONum+1;

            elseif RN <= (sum(rate(1:20))/totalrate)
                [NZE, Conf, CH4productionSP, CH3dissociationSP, CH3oxidationSP, CH3productionSP, CH2dissociationSP, CH3dehydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2oxidationSP,... 
                	H2OproductionSP, OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, CH3hydroxideSP, CH2deoxidationSP, CHhydroxideSP, CHdeoxidationASP,COOHformationASP] = CH3hydroxide(NZE, W, L, Conf, ...
                	CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4dissociationSP, CH3productionSP, CH4oxidationSP, CH3deoxidationSP, H2OdissociationSP, OHproductionSP, ...
                	OHdimerproductionSP, CH4oxidationSP, CH3dehydroxideSP, CH3oxidationSP, CH2dehydroxideSP, CH2oxidationSP, CHdehydroxideSP, CHoxidationASP, COOHdissociationASP);
                CH3hydroxideNum = CH3hydroxideNum+1;

            elseif RN <= (sum(rate(1:21))/totalrate)
                [NZE, Conf, CH4productionSP, CH3dissociationSP, CH3oxidationSP, CH3productionSP, CH2dissociationSP, CH3dehydroxideSP, CH2oxidationSP, H2OproductionSP, ...
                	OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, CH3hydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2deoxidationSP, CHhydroxideSP, CHdeoxidationASP, ...
                	COOHformationASP] = CH3dehydroxide(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH3dissociationSP, CH2productionSP, CH3hydroxideSP, ...
                	CH3oxidationSP, CH2dehydroxideSP, CH2deoxidationSP, H2OadsorptionSP, H2OproductionSP, OHdimerreactionSP, CH3hydroxideSP, CH2hydroxideSP, CHhydroxideSP);
                CH3hydroxideNum = CH3hydroxideNum+1;

            elseif RN <= (sum(rate(1:22))/totalrate)
                [NZE, Conf, CH4productionSP, CH3dissociationSP, CH3productionSP, CH2dissociationSP, CH3dehydroxideSP, H2OproductionSP, OHdissociationSP, OHdimerreactionSP, ...
                	CH4deoxidationSP, CH3hydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2deoxidationSP, CHhydroxideSP, CHdeoxidationASP,COOHformationASP, OHproductionSP, ...
                	OHdimerproductionSP, O2productionSP, CH4oxidationSP, CH3oxidationSP, CH2oxidationSP, CHoxidationASP, CHoxidationBSP, CoxidationSP, COoxidationSP, ...
                	OdiffusionSP] = CH3oxidation(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4dissociationSP, CH3productionSP, CH4oxidationSP, ...
                	CH3dehydroxideSP, OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, CH3deoxidationSP, CH2deoxidationSP, CHdeoxidationASP, CHdeoxidationBSP, CdeoxidationSP, ...
                	COdeoxidationSP,OdiffusionSP);
                CH3oxidationNum = CH3oxidationNum+1;
                ONum = ONum-1;

			elseif RN <= (sum(rate(1:23))/totalrate)
                [NZE, Conf, CH4productionSP, CH3dissociationSP, CH3productionSP, CH2dissociationSP, CH3dehydroxideSP,  H2OproductionSP, OHdissociationSP, OHdimerreactionSP, ...
                	CH4deoxidationSP, CH3hydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2deoxidationSP, CHhydroxideSP, CHdeoxidationASP,COOHformationASP, OHproductionSP, ...
                	OHdimerproductionSP, O2productionSP, CH4oxidationSP, CH3oxidationSP, CH2oxidationSP, CHoxidationASP, CHoxidationBSP, CoxidationSP, COoxidationSP, ...
                	OdiffusionSP] = CH3deoxidation(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH3dissociationSP, CH2productionSP, CH3hydroxideSP, ...
                	CH3oxidationSP, CH2dehydroxideSP, CH2deoxidationSP, H2OdissociationSP, OHproductionSP, OHdimerproductionSP, CH4oxidationSP, CH3dehydroxideSP, ...
                	CH3oxidationSP, CH2dehydroxideSP, CH2oxidationSP, CHdehydroxideSP, CHoxidationASP, COOHdissociationASP);
                CH3deoxidationNum = CH3deoxidationNum+1;
                ONum = ONum+1;

			elseif RN <= (sum(rate(1:24))/totalrate)
                [NZE, Conf, CH3productionSP, CH2dissociationSP, CH3dehydroxideSP, CH2oxidationSP, CH2productionSP, CHdissociationSP, CH2dehydroxideSP, CHhydroxideSP, ...
                	CHoxidationASP, CHoxidationBSP, C2H2productionSP, H2OproductionSP, OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, CH3hydroxideSP, CH3deoxidationSP, ...
                	CH2hydroxideSP, CH2deoxidationSP, CHdeoxidationASP,COOHformationASP] = CH2hydroxide(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3,...
                	CH3dissociationSP, CH2productionSP, CH3hydroxideSP, CH3oxidationSP, CH2deoxidationSP, H2OdissociationSP, OHproductionSP, OHdimerproductionSP, CH4oxidationSP, ...
                	CH3dehydroxideSP, CH3oxidationSP, CH2dehydroxideSP, CH2oxidationSP, CHdehydroxideSP, CHoxidationASP, COOHdissociationASP);
                CH2hydroxideNum = CH2hydroxideNum+1;

            elseif RN <= (sum(rate(1:25))/totalrate)
                [NZE, Conf, CH3productionSP, CH2dissociationSP, CH3dehydroxideSP, CH3deoxidationSP, CH2oxidationSP, CH2productionSP, CHdissociationSP, CH2dehydroxideSP, CHhydroxideSP, ...
                	CHoxidationASP, CHoxidationBSP, C2H2productionSP, H2OproductionSP, OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, CH3hydroxideSP, CH3deoxidationSP, ...
                	CH2hydroxideSP, CH2deoxidationSP, CHdeoxidationASP,COOHformationASP] = CH2dehydroxide(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, ...
                	COOH, C2, C3, CH2dissociationSP, CHproductionSP, CH2oxidationSP, CHdehydroxideSP, CHdeoxidationASP, CHdeoxidationBSP, C2H2dissociationSP, H2OadsorptionSP, ...
                	H2OproductionSP, OHdimerreactionSP, CH3hydroxideSP, CH2hydroxideSP, CHhydroxideSP);
                CH2dehydroxideNum = CH2dehydroxideNum+1; 
                
            elseif RN <= (sum(rate(1:26))/totalrate)
                [NZE, Conf, CH3productionSP, CH2dissociationSP, CH3dehydroxideSP, CH2hydroxideSP, CH2productionSP, CHdissociationSP, CH2dehydroxideSP, CHhydroxideSP, C2H2productionSP,... 
                	H2OproductionSP, OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, CH3hydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2deoxidationSP, CHdeoxidationASP,...
                	COOHformationASP, OHproductionSP, OHdimerproductionSP, O2productionSP, CH4oxidationSP, CH3oxidationSP, CH2oxidationSP, CHoxidationASP, CHoxidationBSP, CoxidationSP, ...
                	COoxidationSP, OdiffusionSP] = CH2oxidation(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH3dissociationSP, CH2productionSP, ...
                	CH3hydroxideSP, CH3oxidationSP, CH2dehydroxideSP, CH2deoxidationSP, OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, CH3deoxidationSP, CH2deoxidationSP, ...
                	CHdeoxidationASP, CHdeoxidationBSP, CdeoxidationSP, COdeoxidationSP,OdiffusionSP);
                CH2oxidationNum = CH2oxidationNum+1;
                ONum = ONum-1;

			elseif RN <= (sum(rate(1:27))/totalrate)
                [NZE, Conf, CH3productionSP, CH2dissociationSP, CH3dehydroxideSP, CH2productionSP, CHdissociationSP, CH2dehydroxideSP, C2H2productionSP, H2OproductionSP, ...
                	OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, CH3hydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2deoxidationSP, CHhydroxideSP, CHdeoxidationASP, ...
                	COOHformationASP, OHproductionSP, OHdimerproductionSP, O2productionSP, CH4oxidationSP, CH3oxidationSP, CH2oxidationSP, CHoxidationASP, CHoxidationBSP, ...
                	CoxidationSP, COoxidationSP, OdiffusionSP] = CH2deoxidation(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH2dissociationSP, ...
                	CHproductionSP, CH2hydroxideSP, CH2oxidationSP, CHdehydroxideSP, CHdeoxidationASP, CHdeoxidationBSP, C2H2dissociationSP, H2OdissociationSP, OHproductionSP, ...
                	OHdimerproductionSP, CH4oxidationSP, CH3dehydroxideSP, CH3oxidationSP, CH2dehydroxideSP, CHoxidationASP, COOHdissociationASP);
                CH2deoxidationNum = CH2deoxidationNum+1;
                ONum = ONum+1;       

            elseif RN <= (sum(rate(1:28))/totalrate)
                [NZE, Conf, CH2productionSP, CHdissociationSP, CH2dehydroxideSP, CHoxidationASP, CHoxidationBSP, C2H2productionSP, H2OproductionSP, OHdissociationSP, ...
                	OHdimerreactionSP, CH4deoxidationSP, CH3hydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2deoxidationSP, CHhydroxideSP, CHdeoxidationASP, ...
                	COOHformationASP] = CHhydroxide(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH2dissociationSP, CHproductionSP, CH2hydroxideSP, ...
                	CH2oxidationSP, CHdeoxidationASP, CHdeoxidationBSP, C2H2dissociationSP, H2OdissociationSP, OHproductionSP, OHdimerproductionSP, ...
                	CH4oxidationSP, CH3dehydroxideSP, CH3oxidationSP, CH2dehydroxideSP, CHdehydroxideSP, CHoxidationASP, COOHdissociationASP);
                CHhydroxideNum = CHhydroxideNum+1;

            elseif RN <= (sum(rate(1:29))/totalrate)
                [NZE, Conf, CH2productionSP, CHdissociationSP, CH2dehydroxideSP, CHoxidationASP, CHoxidationBSP, C2H2productionSP, H2OproductionSP, OHdissociationSP, ...
                	OHdimerreactionSP, CH4deoxidationSP, CH3hydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2deoxidationSP, CHhydroxideSP, CHdeoxidationASP,...
                	COOHformationASP] = CHdehydroxide(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CHdissociationSP, CHhydroxideSP, ...
                	CHoxidationASP, CdeoxidationSP, C2dissociationSP, C3dissociationSP, CdiffusionSP, H2OadsorptionSP, H2OproductionSP, OHdimerreactionSP, ...
                	CH3hydroxideSP, CH2hydroxideSP);
                CHdehydroxideNum = CHdehydroxideNum+1; 

            elseif RN <= (sum(rate(1:30))/totalrate)
                [NZE, Conf, CH2productionSP, CHdissociationSP, CH2dehydroxideSP, C2H2productionSP, H2OproductionSP, OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, ...
                	CH3hydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2deoxidationSP, CHhydroxideSP, CHdeoxidationASP,COOHformationASP, OHproductionSP, OHdimerproductionSP, ...
                	O2productionSP, CH4oxidationSP, CH3oxidationSP, CH2oxidationSP, CHoxidationASP, CHoxidationBSP, CoxidationSP, COoxidationSP, OdiffusionSP] = CHoxidationA(NZE, W, L, Conf, ...
                	CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH2dissociationSP, CHproductionSP, CH2hydroxideSP, CH2oxidationSP, CHdehydroxideSP, CHdeoxidationBSP, ...
                	C2H2dissociationSP, OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, CH3deoxidationSP, CH2deoxidationSP, CHdeoxidationASP, CHdeoxidationBSP, CdeoxidationSP, ...
                	COdeoxidationSP,OdiffusionSP);
                CHoxidationANum = CHoxidationANum+1;
                ONum = ONum-1;

			elseif RN <= (sum(rate(1:31))/totalrate)
                [NZE, Conf, CH2productionSP, CHdissociationSP, CH2dehydroxideSP, C2H2productionSP, H2OproductionSP, OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, ...
                	CH3hydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2deoxidationSP, CHhydroxideSP, CHdeoxidationASP,COOHformationASP, OHproductionSP, OHdimerproductionSP, ...
                	O2productionSP, CH4oxidationSP, CH3oxidationSP, CH2oxidationSP, CHoxidationASP, CHoxidationBSP, CoxidationSP, COoxidationSP, OdiffusionSP] = CHdeoxidationA(NZE, W, L, ...
                	Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CHdissociationSP, CHhydroxideSP, CdeoxidationSP, C2dissociationSP, C3dissociationSP, CdiffusionSP,...
                    H2OdissociationSP, OHproductionSP, OHdimerproductionSP, CH4oxidationSP, CH3dehydroxideSP, CH3oxidationSP, CH2dehydroxideSP, CH2oxidationSP, CHdehydroxideSP, ...
                    CHoxidationASP, COOHdissociationASP);
                CHdeoxidationANum = CHdeoxidationANum+1;
                ONum = ONum+1;

            elseif RN <= (sum(rate(1:32))/totalrate)
                [NZE, Conf, CH4productionSP, CH3productionSP, CHproductionSP, H2OproductionSP, H2productionSP,COOHformationBSP, CH2productionSP, CHdissociationSP, CH2dehydroxideSP, ...
                	CHhydroxideSP, C2H2productionSP, OHproductionSP, OHdimerproductionSP, O2productionSP, CH4oxidationSP, CH3oxidationSP, CH2oxidationSP, CHoxidationASP, ...
                	CHoxidationBSP, CoxidationSP, OdiffusionSP, CHdeoxidationBSP, CdeoxidationSP, COoxidationSP, COdesorptionSP, COOHformationASP,HdiffusionSP] = CHoxidationB(NZE, W, L, Conf, ...
                	CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH2dissociationSP, CHproductionSP, CH2hydroxideSP, CH2oxidationSP, CHdehydroxideSP, ...
                	CHdeoxidationBSP, C2H2dissociationSP, OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, CH3deoxidationSP, CH2deoxidationSP, CHdeoxidationASP, ...
                	CHdeoxidationBSP, CdeoxidationSP, COdeoxidationSP,OdiffusionSP);
                CHoxidationBNum = CHoxidationBNum+1;
                ONum = ONum-1;

			elseif RN <= (sum(rate(1:33))/totalrate)
                [NZE, Conf, CH4productionSP, CH3productionSP, CHproductionSP, H2OproductionSP, H2productionSP,COOHformationBSP, CH2productionSP, CHdissociationSP, ...
                	CH2dehydroxideSP, CHhydroxideSP, C2H2productionSP, OHproductionSP, OHdimerproductionSP, O2productionSP, CH4oxidationSP, CH3oxidationSP, CH2oxidationSP, ...
                	CHoxidationASP, CHoxidationBSP, CoxidationSP, COoxidationSP, OdiffusionSP, CHdeoxidationBSP, CdeoxidationSP, COoxidationSP, COdesorptionSP, ...
                	COOHformationASP] = CHdeoxidationB(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4dissociationSP, CH3dissociationSP, ...
                	CH2dissociationSP, CHdissociationSP, H2OdissociationSP, OHdissociationSP, CHoxidationASP, COOHdissociationBSP, HdiffusionSP, CHoxidationBSP, CoxidationSP, ...
                	COdeoxidationSP, COadsorptionSP, COOHdissociationASP);
                CHdeoxidationBNum = CHdeoxidationBNum+1;
                ONum = ONum+1;

            elseif RN <= (sum(rate(1:34))/totalrate)
                [NZE, Conf, CH3dissociationSP, CH2dissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, CH4oxidationSP, CdeoxidationSP, COdeoxidationSP, ...
                	COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, OdiffusionSP, CdiffusionSP, ...
                	C3diffusionSP, CH2productionSP, CHdissociationSP, CH2dehydroxideSP, CHhydroxideSP, CHoxidationASP, CHoxidationBSP, C2H2productionSP, ...
                	C2H2dissociationSP] = C2H2production(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH2dissociationSP, CHproductionSP, ...
                	CH2hydroxideSP, CH2oxidationSP, CHdehydroxideSP, CHdeoxidationASP, CHdeoxidationBSP, C2H2dissociationSP);
                C2H2productionNum = C2H2productionNum+1;

            elseif RN <= (sum(rate(1:35))/totalrate)
                [NZE, Conf, CH3dissociationSP, CH2dissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, CH4oxidationSP, CdeoxidationSP, COdeoxidationSP, ...
                	COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, OdiffusionSP, CdiffusionSP, ...
                	C3diffusionSP, CH2productionSP, CHdissociationSP, CH2dehydroxideSP, CHhydroxideSP, CHoxidationASP, CHoxidationBSP, C2H2productionSP, ...
                	C2H2dissociationSP] = C2H2dissociation(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4productionSP, CH3productionSP, ...
                	CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, O2productionSP, H2productionSP,CH4deoxidationSP, C2H2productionSP, CoxidationSP, ...
                	COoxidationSP, COdesorptionSP, CO2desorptionSP, COOHformationASP, COOHformationBSP, C2formationSP, C3formationSP,HdiffusionSP, OdiffusionSP, CdiffusionSP, ...
                	C3diffusionSP, C2H2productionSP);
                C2H2dissociationNum = C2H2dissociationNum+1;

            elseif RN <= (sum(rate(1:36))/totalrate)
                [NZE, Conf, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, C2H2dissociationSP, ...
                	COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, CdiffusionSP, ...
                	C3diffusionSP, OHproductionSP, OHdimerproductionSP, O2productionSP, CH4oxidationSP, CH3oxidationSP, CH2oxidationSP, CHoxidationASP, CHoxidationBSP, ...
                	CoxidationSP, COoxidationSP, OdiffusionSP, CHdeoxidationBSP, CdeoxidationSP, COoxidationSP, COdesorptionSP, COOHformationASP] = Coxidation(NZE, W, L, Conf, ...
                	CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CHdissociationSP, CHhydroxideSP, CHoxidationASP, C2dissociationSP, C3dissociationSP, ...
                	CdiffusionSP, OHdissociationSP, OHdimerreactionSP, CH4deoxidationSP, CH3deoxidationSP, CH2deoxidationSP, CHdeoxidationASP, CHdeoxidationBSP, ...
                	CdeoxidationSP, COdeoxidationSP,OdiffusionSP);
                CoxidationNum = CoxidationNum+1;
                ONum = ONum-1;

			elseif RN <= (sum(rate(1:37))/totalrate)
                [NZE, Conf, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, C2H2dissociationSP, COdeoxidationSP, ...
                	COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, CdiffusionSP, C3diffusionSP, ...
                	OHproductionSP, OHdimerproductionSP, O2productionSP, CH4oxidationSP, CH3oxidationSP, CH2oxidationSP, CHoxidationASP, CHoxidationBSP, CoxidationSP, COoxidationSP, ...
                	OdiffusionSP, CHdeoxidationBSP, CdeoxidationSP, COoxidationSP, COdesorptionSP, COOHformationASP] = Cdeoxidation(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, ...
                	O, CO, CO2, COOH, C2, C3, CH4productionSP, CH3productionSP, CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, O2productionSP, H2productionSP,...
                	CH4deoxidationSP, C2H2productionSP, CoxidationSP, COoxidationSP, COdesorptionSP, CO2desorptionSP, COOHformationASP, COOHformationBSP, C2formationSP, C3formationSP,...
                	HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP, CHoxidationBSP, COdeoxidationSP, COadsorptionSP, COOHdissociationASP);
                CdeoxidationNum = CdeoxidationNum+1;
                ONum = ONum+1;

            elseif RN <= (sum(rate(1:38))/totalrate)
                [NZE, Conf, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, C2H2dissociationSP, CdeoxidationSP, ...
                	COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, OdiffusionSP, ...
                	CdiffusionSP, C3diffusionSP, OHproductionSP, OHdimerproductionSP, O2productionSP, CH4oxidationSP, CH3oxidationSP, CH2oxidationSP, CHoxidationASP, CHoxidationBSP, ...
                	CoxidationSP, COoxidationSP, OdiffusionSP, CHdeoxidationBSP, CdeoxidationSP, COdesorptionSP, COOHformationASP, COdeoxidationSP, CO2desorptionSP, ...
                	COOHformationASP] = COoxidation(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4productionSP, CH3productionSP, CH2productionSP, ...
                	CHproductionSP, H2OproductionSP, OHproductionSP, O2productionSP, H2productionSP, CH4deoxidationSP, C2H2productionSP, CoxidationSP, COoxidationSP, COdesorptionSP, ...
                	CO2desorptionSP, COOHformationBSP, C2formationSP, C3formationSP,HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP);
                COoxidationNum = COoxidationNum+1;
                ONum = ONum-1;

			elseif RN <= (sum(rate(1:39))/totalrate)
                [NZE, Conf, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, C2H2dissociationSP, COadsorptionSP, ...
                	CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, CdiffusionSP, C3diffusionSP, ...
                	OHproductionSP, OHdimerproductionSP, O2productionSP, CH4oxidationSP, CH3oxidationSP, CH2oxidationSP, CHoxidationASP, CHoxidationBSP, CoxidationSP, ...
                	COoxidationSP, OdiffusionSP, CHdeoxidationBSP, CdeoxidationSP, COdesorptionSP, COOHformationASP, COdeoxidationSP, CO2desorptionSP, ...
                	COOHformationASP] = COdeoxidation(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4productionSP, CH3productionSP, CH2productionSP, ...
                	CHproductionSP, H2OproductionSP, OHproductionSP, O2productionSP, H2productionSP,CH4deoxidationSP, C2H2productionSP, CoxidationSP, COoxidationSP, COdesorptionSP, ...
                	CO2desorptionSP, COOHformationASP, COOHformationBSP, C2formationSP, C3formationSP, HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP,...
                    COoxidationSP, CO2adsorptionSP, COOHdissociationBSP);
                COdeoxidationNum = COdeoxidationNum+1;
                ONum = ONum+1;

            elseif RN <= (sum(rate(1:40))/totalrate)
                [NZE, Conf, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, CH4oxidationSP, C2H2dissociationSP, ...
                	COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, OdiffusionSP, ...
                	CdiffusionSP, C3diffusionSP, CHdeoxidationBSP, CdeoxidationSP, COoxidationSP, COdesorptionSP, COOHformationASP] = COdesorption(NZE, W, L, Conf, CH3, CH2, CH, ...
                	C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CHoxidationBSP, CoxidationSP, COdeoxidationSP, COadsorptionSP, COOHdissociationASP);
                COdesorptionNum = COdesorptionNum+1;

            elseif RN <= (sum(rate(1:41))/totalrate)
                [NZE, Conf, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, CH4oxidationSP, C2H2dissociationSP, ...
                	CdeoxidationSP, COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, ...
                	OdiffusionSP, CdiffusionSP, C3diffusionSP, CHdeoxidationBSP, CdeoxidationSP, COoxidationSP, COdesorptionSP, COOHformationASP] = COadsorption(NZE, W, L, Conf, CH3, ...
                	CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4productionSP, CH3productionSP, CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, ...
                	O2productionSP, H2productionSP,CH4deoxidationSP, C2H2productionSP, CoxidationSP, COoxidationSP, COdesorptionSP, CO2desorptionSP, COOHformationASP, COOHformationBSP, ...
                	C2formationSP, C3formationSP,HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP);
                COadsorptionNum = COadsorptionNum+1;

            elseif RN <= (sum(rate(1:42))/totalrate)
                [NZE, Conf, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, CH4oxidationSP, C2H2dissociationSP, ...
                	CdeoxidationSP, COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, ...
                	OdiffusionSP, CdiffusionSP, C3diffusionSP, COdeoxidationSP, CO2desorptionSP, COOHformationASP] = CO2desorption(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, ...
                	CO, CO2, COOH, C2, C3, COoxidationSP, CO2adsorptionSP, COOHdissociationBSP);
                CO2desorptionNum = CO2desorptionNum+1;

            elseif RN <= (sum(rate(1:43))/totalrate)
                [NZE, Conf, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, CH4oxidationSP, C2H2dissociationSP, ...
                	CdeoxidationSP, COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, ...
                	OdiffusionSP, CdiffusionSP, C3diffusionSP, COdeoxidationSP, CO2desorptionSP, COOHformationASP] = CO2adsorption(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, ...
                	CO, CO2, COOH, C2, C3, CH4productionSP, CH3productionSP, CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, O2productionSP, H2productionSP, ...
                	CH4deoxidationSP, C2H2productionSP, CoxidationSP, COoxidationSP, COdesorptionSP, CO2desorptionSP, COOHformationASP, COOHformationBSP, C2formationSP, C3formationSP, ...
                	HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP);
                CO2adsorptionNum = CO2adsorptionNum+1;

            elseif RN <= (sum(rate(1:44))/totalrate)
                [NZE, Conf, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, CH4oxidationSP, C2H2dissociationSP, ...
                	CdeoxidationSP, COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, OdiffusionSP, CdiffusionSP, ...
                	C3diffusionSP, H2OproductionSP, OHdimerreactionSP, CH4deoxidationSP, CH3hydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2deoxidationSP, CHhydroxideSP, ...
                	CHdeoxidationASP, CHdeoxidationBSP, COoxidationSP, COdesorptionSP, COOHformationASP, COOHdissociationASP, COOHdissociationBSP] = COOHformationA(NZE, W, L, Conf, CH3, ...
                	CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, H2OdissociationSP, OHproductionSP, OHdimerproductionSP, CH4oxidationSP, CH3dehydroxideSP, CH3oxidationSP, ...
                	CH2dehydroxideSP, CH2oxidationSP, CHdehydroxideSP, CHoxidationASP, COOHdissociationASP, CHoxidationBSP, CoxidationSP, COdeoxidationSP, COadsorptionSP);
                COOHformationANum = COOHformationANum+1;
                CONum = CONum-1;

            elseif RN <= (sum(rate(1:45))/totalrate)
                [NZE, Conf, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, CH4oxidationSP, C2H2dissociationSP, COdeoxidationSP, ...
                	COadsorptionSP, CO2adsorptionSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP, H2OproductionSP, OHdissociationSP, ...
                	OHdimerreactionSP, CH4deoxidationSP, CH3hydroxideSP, CH3deoxidationSP, CH2hydroxideSP, CH2deoxidationSP, CHhydroxideSP, CHdeoxidationASP,COOHformationASP, ...
                	CHdeoxidationBSP, CdeoxidationSP, COoxidationSP, COdesorptionSPCOO, HdissociationASP, COOHdissociationBSP] = COOHdissociationA(NZE, W, L, Conf, CH3, CH2, ...
                	CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4productionSP, CH3productionSP, CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, O2productionSP, ...
                	H2productionSP,CH4deoxidationSP, C2H2productionSP, CoxidationSP, COoxidationSP, COdesorptionSP, CO2desorptionSP, COOHformationASP, COOHformationBSP, C2formationSP, ...
                	C3formationSP,HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP);
                COOHdissociationANum = COOHdissociationANum+1;
                CONum = CONum+1;

            elseif RN <= (sum(rate(1:46))/totalrate)
                [NZE, Conf, CH4productionSP, CH3productionSP, CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, H2productionSP, CHdeoxidationBSP, COOHformationBSP, ...
                	CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, CH4oxidationSP, C2H2dissociationSP, CdeoxidationSP, ...
                	COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, OdiffusionSP, ...
                	CdiffusionSP, C3diffusionSP, CO2desorptionSP, COOHformationASP] = COOHformationB(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3,...
                	CH4dissociationSP, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OdissociationSP, OHdissociationSP, CHoxidationASP, HdiffusionSP,...
                	COoxidationSP, CO2adsorptionSP, COOHdissociationBSP);
                COOHformationBNum = COOHformationBNum+1;
                CO2Num = CO2Num-1;
                HNum = HNum-1;

            elseif RN <= (sum(rate(1:47))/totalrate)
                [NZE, Conf, CH4productionSP, CH3productionSP, CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, H2productionSP, CHdeoxidationBSP,COOHformationBSP, ...
                	CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, CH4oxidationSP, C2H2dissociationSP, CdeoxidationSP, ...
                	COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, OdiffusionSP,... 
                	CdiffusionSP, C3diffusionSP, COdeoxidationSP, CO2desorptionSP, COOHformationASP, COOHdissociationASP, COOHdissociationBSP] = COOHdissociationB(NZE, W, L, Conf, ...
                	CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4productionSP, CH3productionSP, CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, ...
                	O2productionSP, H2productionSP,CH4deoxidationSP, C2H2productionSP, CoxidationSP, COoxidationSP, COdesorptionSP, CO2desorptionSP, COOHformationASP, COOHformationBSP, ...
                	C2formationSP, C3formationSP,HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP);
                COOHdissociationBNum = COOHdissociationBNum+1;
                CO2Num = CO2Num+1;
                HNum = HNum+1;

            elseif RN <= (sum(rate(1:48))/totalrate)
                [NZE, Conf, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, CH4oxidationSP, C2H2dissociationSP, ...
                	CdeoxidationSP, COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, ...
                	OdiffusionSP, CdiffusionSP, C3diffusionSP, C2dissociationSP, C3formationSP] = C2formation(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3,...
                	CHdissociationSP, CHhydroxideSP, CHoxidationASP, CdeoxidationSP, C2dissociationSP, C3dissociationSP, CdiffusionSP);
                C2formationNum = C2formationNum+1;
                CNum = CNum-2;
                C2Num = C2Num+1;

            elseif RN <= (sum(rate(1:49))/totalrate)
                [NZE, Conf, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, CH4oxidationSP, C2H2dissociationSP, ...
                	CdeoxidationSP, COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, ...
                	OdiffusionSP, CdiffusionSP, C3diffusionSP, C3formationSP] = C2dissociation(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3,...
                	CH4productionSP, CH3productionSP, CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, O2productionSP, H2productionSP,CH4deoxidationSP, ...
                	C2H2productionSP, CoxidationSP, COoxidationSP, COdesorptionSP, CO2desorptionSP, COOHformationASP, COOHformationBSP, C2formationSP, C3formationSP,HdiffusionSP, ...
                	OdiffusionSP, CdiffusionSP, C3diffusionSP, C3dissociationSP);
                C2dissociationNum = C2dissociationNum+1;
                CNum = CNum+2;
                C2Num = C2Num-1;

            elseif RN <= (sum(rate(1:50))/totalrate)
                [NZE, Conf, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, CH4oxidationSP, C2H2dissociationSP, ...
                	CdeoxidationSP, COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, ...
                	OdiffusionSP, CdiffusionSP, C3diffusionSP, C3formationSP] = C3formation(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CHdissociationSP, ...
                	CHhydroxideSP, CHoxidationASP, CdeoxidationSP, C2dissociationSP, C3dissociationSP, CdiffusionSP, C2formationSP);
                C3formationNum = C3formationNum+1;
                CNum = CNum-1;
                C2Num = C2Num-1;
                C3Num = C3Num+1;

            elseif RN <= (sum(rate(1:51))/totalrate)
                [NZE, Conf, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, CH4oxidationSP, C2H2dissociationSP, ...
                	CdeoxidationSP, COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, HdiffusionSP, CdiffusionSP, C3diffusionSP, ...
                	C2dissociationSP, C3formationSP, C3dissociationSP] = C3dissociation(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4productionSP, ...
                	CH3productionSP, CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, O2productionSP, H2productionSP,CH4deoxidationSP, C2H2productionSP, ...
                	CoxidationSP, COoxidationSP, COdesorptionSP, CO2desorptionSP, COOHformationASP, COOHformationBSP, C2formationSP, C3formationSP,HdiffusionSP, OdiffusionSP, ...
                	CdiffusionSP, C3diffusionSP);
                C3dissociationNum = C3dissociationNum+1;
                CNum = CNum+1;
                C2Num = C2Num+1;
                C3Num = C3Num-1;

            elseif RN <= (sum(rate(1:52))/totalrate)
                [NZE, Conf, CH4productionSP, CH3productionSP, CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, H2productionSP, CHdeoxidationBSP, COOHformationBSP, ...
                	CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, CH4oxidationSP, C2H2dissociationSP, CdeoxidationSP, ...
                	COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, OdiffusionSP, ...
                	CdiffusionSP, C3diffusionSP] = Hdiffusion(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4dissociationSP, CH3dissociationSP, ...
                	CH2dissociationSP, CHdissociationSP, H2OdissociationSP, OHdissociationSP, CHoxidationASP, COOHdissociationBSP, CH4productionSP, CH3productionSP, ...
                	CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, O2productionSP, H2productionSP,CH4deoxidationSP, C2H2productionSP, CoxidationSP, COoxidationSP, ...
                	COdesorptionSP, CO2desorptionSP, COOHformationASP, COOHformationBSP, C2formationSP, C3formationSP, HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP);
                HdiffusionNum = HdiffusionNum+1;

            elseif RN <= (sum(rate(1:53))/totalrate)
                [NZE, Conf, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, C2H2dissociationSP, CdeoxidationSP, ...
                	COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, CdiffusionSP, ...
                	C3diffusionSP, OHproductionSP, OHdimerproductionSP, O2productionSP, CH4oxidationSP, CH3oxidationSP, CH2oxidationSP, CHoxidationASP, CHoxidationBSP, CoxidationSP, ...
                	COoxidationSP, OdiffusionSP] = Odiffusion(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4productionSP, CH3productionSP, CH2productionSP, ...
                	CHproductionSP, H2OproductionSP, OHproductionSP, O2productionSP, H2productionSP,CH4deoxidationSP, C2H2productionSP, CoxidationSP, COoxidationSP, COdesorptionSP, ...
                	CO2desorptionSP, COOHformationASP, COOHformationBSP, C2formationSP, C3formationSP,HdiffusionSP, CdiffusionSP, C3diffusionSP, OHdissociationSP, ...
                	OHdimerreactionSP, CH3deoxidationSP, CH2deoxidationSP, CHdeoxidationASP, CHdeoxidationBSP, CdeoxidationSP, COdeoxidationSP,OdiffusionSP);
                OdiffusionNum = OdiffusionNum+1;

            elseif RN <= (sum(rate(1:54))/totalrate)
                [NZE, Conf, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, CH4oxidationSP, C2H2dissociationSP, ...
                	CdeoxidationSP, COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, ...
                	OdiffusionSP, CdiffusionSP, C3diffusionSP] = Cdiffusion(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3, CH4productionSP, CH3productionSP, ...
                	CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, O2productionSP, H2productionSP,CH4deoxidationSP, C2H2productionSP, CoxidationSP, COoxidationSP, ...
                	COdesorptionSP, CO2desorptionSP, COOHformationASP, COOHformationBSP, C2formationSP, C3formationSP,HdiffusionSP, OdiffusionSP, CdiffusionSP, C3diffusionSP, ...
                	CHdissociationSP, CHhydroxideSP, CHoxidationASP, CdeoxidationSP, C2dissociationSP, C3dissociationSP, CdiffusionSP);
                CdiffusionNum = CdiffusionNum+1;

            elseif RN <= (sum(rate(1:55))/totalrate)
                [NZE, Conf, CH3dissociationSP, CH2dissociationSP, CHdissociationSP, H2OadsorptionSP, H2OdissociationSP, OHdissociationSP, CH4oxidationSP, C2H2dissociationSP, ...
                	CdeoxidationSP, COdeoxidationSP, COadsorptionSP, CO2adsorptionSP, COOHdissociationASP, COOHdissociationBSP, C2dissociationSP, C3dissociationSP, HdiffusionSP, ...
                	OdiffusionSP, CdiffusionSP, C3diffusionSP, C3dissociationSP] = C3diffusion(NZE, W, L, Conf, CH3, CH2, CH, C, H, H2O, OH, O, CO, CO2, COOH, C2, C3,...
                	CH4productionSP, CH3productionSP, CH2productionSP, CHproductionSP, H2OproductionSP, OHproductionSP, O2productionSP, H2productionSP,CH4deoxidationSP, ...
                	C2H2productionSP, CoxidationSP, COoxidationSP, COdesorptionSP, CO2desorptionSP, COOHformationASP, COOHformationBSP, C2formationSP, C3formationSP,HdiffusionSP, ...
                	OdiffusionSP, CdiffusionSP, C3diffusionSP);
                C3diffusionNum = C3diffusionNum+1;
            
            end
            RN2=rand(1);      
            t=t+(-1/totalrate*log(RN2));

    pint=rem(step,PS);
    switch(pint)
        case(0)
             count=count+1;
             rate1=0.004277*(CO2num+COnum)/d^3/t*60;
             rate2=0.008626*(CO2num+COnum)/d/t;
             
             fprintf('count %d\n',count)
             fprintf('CH4dissociationNum %d\n',CH4dissociationNum)
             fprintf('CH4productionNum %d\n',CH4productionNum) 
             fprintf('difference %d\n',CH4dissociationNum-CH4productionNum)
             fprintf('CH3dissociationNum %d\n',CH3dissociationNum)
             %fprintf('CH3productionNum %d\n',CH3productionNum)
             %fprintf('CH2dissociationNum %d\n',CH2dissociationNum)
             %fprintf('CHdissociationNum %d\n',CHdissociationNum)
             fprintf('CHproductionNum %d\n',CHproductionNum)
             fprintf('CH3on %d\n',CH3on)
             
             %fprintf('CH3diffusionNum %d\n',CH3diffusionNum)
             fprintf('HdiffusionNum %d\n',HdiffusionNum)
             fprintf('CdiffusionNum %d\n',CdiffusionNum)
             fprintf('C3diffusionNum %d\n',C3diffusionNum)
             fprintf('H2productionNum %d\n',H2productionNum)
             fprintf('H number on surface %d\n',HNum)
             
             fprintf('CNum %d\n',CNum)
             %fprintf('CCNTNum %d\n',CCNTNum)
             fprintf('coverage %4.3e\n',coverage)
             fprintf('t %4.3e\n',t)
             fprintf('diameter nm %4.3e\n',d)
             fprintf('rate1 gC/gcat/min %4.3e\n',rate1)
             fprintf('rate2 nm/s %4.3e\n',rate2)
             fprintf('trap1 %d\n',trap1)
             fprintf('trap2 %d\n',trap2)
             
             g = [g;t rate1 rate2 CO2num coverage];
             outp=[W,d,T,PS];
             fileID = fopen ('KMCdata.txt','w');
             fprintf(fileID,'%1s %5s %5s %5s\r\n','lattice','diameter','Temperature','PS');
             fprintf(fileID,'%5.2f %8.2f %8.2f %8.2f\r\n', outp);
             fprintf(fileID,'%1s %16s %8s %12s %12s\r\n','t(s)','gC/gcat/min','nm/s', 'CXFNum', 'coverage');
             fprintf(fileID,'%5.3e %11.5f %11.5f %11.5f %11.3e\r\n', g'); 
             fclose(fileID);
             
    end
   %toc
    
end
